version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: baseuni
    hostname: baseuni
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autosdb
      POSTGRES_HOST: baseuni 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - datalogger_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - datalogger_net

  universidades:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=uni
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: ["sh", "-c", "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0"]
    networks:
      - datalogger_net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: c:/Users/jorge/datapng

networks:
  datalogger_net:
    driver: bridge