apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: universidades
  name: universidades
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: universidades
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: universidades
    spec:
      containers:
        - args:
            - sh
            - -c
            - /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: uni
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: universidades
          name: universidades
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
